<?php

namespace App\AI\Tools;

use App\AI\Contracts\AiToolInterface;
use App\AI\DTOs\AiContextData;
use App\AI\Reporting\Services\AiIntelligenceReportService;
use App\Models\User;
use InvalidArgumentException;

/**
 * ai.reports.view — a structured management intelligence report for the acting
 * user's own organization.
 *
 * Read-only and deterministic: the tool delegates entirely to
 * AiIntelligenceReportService, which reuses the existing authoritative
 * reporting services, Phase 11.8 predictions and Phase 11.9 insights. Tenant
 * and branch scope come exclusively from the trusted context — the arguments
 * are limited to a report type and a reporting period, and the policy has
 * already rejected any tenant-bearing key. The tool never writes a business
 * record, executes a financial action or computes a figure the reporting layer
 * did not already compute.
 */
class IntelligenceReportTool implements AiToolInterface
{
    public function __construct(
        private readonly AiIntelligenceReportService $reports,
    ) {}

    public function execute(User $user, AiContextData $context, array $arguments): array
    {
        $reportType = (string) ($arguments['report_type'] ?? 'executive_portfolio');
        $periodType = (string) ($arguments['period'] ?? 'this_month');

        try {
            $report = $this->reports->generate(
                context: $context,
                user: $user,
                reportType: $reportType,
                periodType: $periodType,
                from: isset($arguments['from']) ? (string) $arguments['from'] : null,
                to: isset($arguments['to']) ? (string) $arguments['to'] : null,
                withNarrative: false,
                persist: false,
            );
        } catch (InvalidArgumentException) {
            // An unsupported type/period is reported as unavailable rather than
            // guessed, and no record is written.
            return [
                'as_of' => now()->toISOString(),
                'available' => false,
                'reason' => 'The requested report could not be produced. It may not exist or may not be authorized for this role.',
                'note' => 'Management intelligence reports are computed by the FinancePro reporting service and are never generated by the AI.',
            ];
        }

        $data = (array) $report->report_data;

        return [
            'as_of' => now()->toISOString(),
            'available' => true,
            'report_type' => $data['report_type'] ?? $reportType,
            'report_type_label' => $data['report_type_label'] ?? null,
            'period' => $data['period'] ?? null,
            'data_through' => $data['data_through'] ?? null,
            'generated_at' => $data['generated_at'] ?? null,
            'sections' => array_map(fn (array $section) => $this->sectionPayload($section), (array) ($data['sections'] ?? [])),
            'data_quality' => $data['data_quality'] ?? [],
            'note' => 'Every figure below was computed by the FinancePro reporting service from authoritative records. '
                .'Facts are observed values, trends are deterministic period comparisons, predictive signals are Phase 11.8 '
                .'statistical outlooks (indications, never guarantees) and proactive insights are Phase 11.9 rule-based '
                .'advisories for a human decision. The assistant explains this data and never changes it.',
        ];
    }

    /**
     * The classified section payload. Facts, trends, predictions and advisories
     * stay in their own group so the provider can never see an advisory filed
     * as a fact.
     *
     * @param  array<string, mixed>  $section
     * @return array<string, mixed>
     */
    protected function sectionPayload(array $section): array
    {
        return [
            'key' => $section['key'] ?? null,
            'title' => $section['title'] ?? null,
            'facts' => array_map(fn (array $datum) => $this->datumPayload($datum), (array) ($section['facts'] ?? [])),
            'trends' => array_map(fn (array $datum) => $this->datumPayload($datum), (array) ($section['trends'] ?? [])),
            'predictions' => array_map(fn (array $datum) => $this->datumPayload($datum), (array) ($section['predictions'] ?? [])),
            'advisories' => array_map(fn (array $datum) => $this->datumPayload($datum), (array) ($section['advisories'] ?? [])),
            'data_quality' => $section['data_quality'] ?? [],
            'counts' => $section['counts'] ?? [],
        ];
    }

    /**
     * @param  array<string, mixed>  $datum
     * @return array<string, mixed>
     */
    protected function datumPayload(array $datum): array
    {
        return [
            'label' => $datum['label'] ?? null,
            'value' => $datum['value'] ?? null,
            'classification' => $datum['classification'] ?? null,
            'classification_label' => $datum['classification_label'] ?? null,
            'unit' => $datum['unit'] ?? null,
            'previous_value' => $datum['previous_value'] ?? null,
            'absolute_change' => $datum['absolute_change'] ?? null,
            'percentage_change' => $datum['percentage_change'] ?? null,
            'direction' => $datum['direction_label'] ?? null,
            'note' => $datum['note'] ?? null,
            'source' => $datum['source'] ?? null,
            'detail' => $datum['meta'] ?? null,
        ];
    }
}
