<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report->report_type->label() }} - {{ config('app.name') }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{-- The print view is intentionally self-contained: no navigation, no
         interactive controls, and print styles that keep a section from being
         split across two pages. --}}
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #1a1a1a; margin: 24px; font-size: 13px; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 15px; margin: 20px 0 6px; padding-bottom: 4px; border-bottom: 1px solid #d8dee6; }
        .meta { color: #555; font-size: 12px; }
        .meta table { border-collapse: collapse; }
        .meta td { padding: 1px 14px 1px 0; vertical-align: top; }
        .badge { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 10px; border: 1px solid #adb5bd; }
        .badge-fact { background: #e7f1ff; }
        .badge-trend { background: #e3fafc; }
        .badge-prediction { background: #fff3cd; }
        .badge-advisory { background: #f1f3f5; }
        table.datum { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        table.datum th, table.datum td { border: 1px solid #dee2e6; padding: 4px 6px; text-align: left; vertical-align: top; }
        table.datum th { background: #f8f9fa; width: 34%; }
        .value { font-weight: 600; }
        .note { color: #555; font-style: italic; font-size: 11px; }
        .narrative { background: #fffbe6; border: 1px solid #ffe08a; padding: 10px; white-space: pre-line; }
        .caveat { margin-top: 18px; font-size: 11px; color: #555; border-top: 1px solid #d8dee6; padding-top: 8px; }
        .quality { background: #f8f9fa; border-left: 3px solid #adb5bd; padding: 6px 10px; margin: 6px 0; font-size: 11px; }
        section { page-break-inside: avoid; }
        @media print { .no-print { display: none; } body { margin: 0; } }
    </style>
</head>
<body>
    <div class="no-print mb-3">
        <button type="button" onclick="window.print()">Print this report</button>
    </div>

    <h1>{{ config('app.name') }} — {{ $report->report_type->label() }}</h1>
    <div class="meta">
        {{ $report->organization?->name }}
        @if ($report->branch) &middot; {{ $report->branch->name }} @else &middot; All authorized branches @endif
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Reporting period</strong></td>
                <td>{{ $report->period_start->toFormattedDateString() }} to {{ $report->period_end->toFormattedDateString() }}</td>
                <td><strong>Comparison period</strong></td>
                <td>
                    @if ($report->previous_period_start)
                        {{ $report->previous_period_start->toFormattedDateString() }} to {{ $report->previous_period_end->toFormattedDateString() }}
                    @else
                        Not available
                    @endif
                </td>
            </tr>
            <tr>
                <td><strong>Data through</strong></td>
                <td>{{ $report->data_through?->toFormattedDateString() }}</td>
                <td><strong>Generated</strong></td>
                <td>{{ $report->generated_at?->format('j M Y, H:i') }}</td>
            </tr>
        </table>
        <div class="note">The reporting period is the window described; data through is the newest authoritative record observed. Later data is never implied to belong to the reporting period.</div>
    </div>

    @if (count($dataQuality) > 0)
        <div class="quality">
            <strong>Data quality and limitations</strong>
            <ul>
                @foreach ($dataQuality as $note)
                    <li>{{ $note }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if (is_array($report->narrative) && ($report->narrative['available'] ?? false) === true)
        <section>
            <h2>AI narrative (explanatory only)</h2>
            <div class="note mb-1">
                Generated by {{ $report->narrative['provider'] ?? 'the AI provider' }} ({{ $report->narrative['model'] ?? 'unknown model' }}).
                This narrative explains the figures below; it is not a financial figure itself.
            </div>
            <div class="narrative">{{ $report->narrative['summary'] }}</div>
        </section>
    @endif

    @if ($sections === [])
        <p class="meta">This report contains no data for the selected scope and period.</p>
    @endif

    @foreach ($sections as $section)
        <section>
            <h2>{{ $section['title'] ?? 'Section' }}</h2>

            @foreach (['facts', 'trends', 'predictions', 'advisories'] as $group)
                @if (count($section[$group] ?? []) > 0)
                    <table class="datum">
                        <tbody>
                            @foreach ($section[$group] as $datum)
                                <tr>
                                    <th>
                                        {{ $datum['label'] ?? 'Untitled' }}
                                        <span class="badge badge-{{ $datum['classification'] ?? 'fact' }}">{{ $datum['classification_label'] ?? 'Fact' }}</span>
                                    </th>
                                    <td>
                                        @php
                                            $format = $datum['format'] ?? 'text';
                                            $value = $datum['value'] ?? null;
                                            // The persisted meta payload is a JSON array.
                                            $details = (object) (($datum['meta'] ?? []) ?: []);
                                        @endphp
                                        @if ($value !== null)
                                            <span class="value">
                                                @if ($format === 'money')
                                                    {{ config('intelligence-reporting.currency', 'TZS') }} {{ number_format((float) $value, 2) }}
                                                @elseif ($format === 'percent')
                                                    {{ number_format((float) $value, 2) }}%
                                                @elseif ($format === 'boolean')
                                                    {{ $value ? 'Yes' : 'No' }}
                                                @elseif (in_array($format, ['integer', 'decimal'], true))
                                                    {{ number_format((float) $value, 2) }}
                                                @else
                                                    {{ $value }}
                                                @endif
                                            </span>
                                        @endif

                                        @if (($datum['classification'] ?? '') === 'trend')
                                            <div class="note">
                                                @if (($datum['direction'] ?? '') === 'unavailable' || ($datum['direction'] ?? null) === null)
                                                    No previous comparable period data — the comparison could not be calculated.
                                                @else
                                                    {{ $datum['direction_label'] }}:
                                                    change {{ $datum['absolute_change'] !== null ? number_format((float) $datum['absolute_change'], 2) : 'n/a' }}
                                                    ({{ $datum['percentage_change'] !== null ? number_format((float) $datum['percentage_change'], 2).'%' : 'n/a' }})
                                                    from previous {{ $datum['previous_value'] !== null ? number_format((float) $datum['previous_value'], 2) : 'n/a' }}
                                                @endif
                                            </div>
                                        @endif

                                        @if (($datum['classification'] ?? '') === 'prediction')
                                            <div class="note">
                                                {{ ucfirst((string) ($details->status_label ?? 'unknown')) }} ·
                                                {{ ucfirst((string) ($details->confidence ?? 'n/a')) }} confidence ·
                                                {{ ucfirst((string) ($details->data_quality ?? 'n/a')) }} data ·
                                                horizon {{ $details->horizon ?? 'n/a' }}
                                                @if (($details->value ?? null) !== null)
                                                    · outlook {{ config('intelligence-reporting.currency', 'TZS') }} {{ number_format((float) $details->value, 2) }}
                                                @endif
                                            </div>
                                            @if (! empty($details->explanation))
                                                <div>{{ $details->explanation }}</div>
                                            @endif
                                        @endif

                                        @if (($datum['classification'] ?? '') === 'advisory')
                                            <div class="note">
                                                {{ ucfirst((string) ($details->severity_label ?? 'unknown')) }} ·
                                                {{ ucfirst((string) ($details->type_label ?? 'insight')) }} ·
                                                {{ ucfirst((string) ($details->status_label ?? 'open')) }}
                                            </div>
                                            @if (! empty($details->summary))
                                                <div>{{ $details->summary }}</div>
                                            @endif
                                            @if (! empty($details->recommendation))
                                                <div><strong>Suggested:</strong> {{ $details->recommendation }}</div>
                                            @endif
                                        @endif

                                        @if (! empty($datum['note']))
                                            <div class="note">{{ $datum['note'] }}</div>
                                        @endif
                                        <div class="note">Source: {{ $datum['source'] ?? 'FinancePro' }}</div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
            @endforeach

            @foreach ($section['rows'] ?? [] as $row)
                @if (count($row['rows'] ?? []) > 0)
                    <h2>{{ $row['label'] ?? 'Detail' }}</h2>
                    <table class="datum">
                        <tbody>
                            @foreach ($row['rows'] as $line)
                                <tr>
                                    @foreach ($line as $cell)
                                        <td>{{ is_array($cell) ? json_encode($cell) : $cell }}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
            @endforeach

            @if (count($section['data_quality'] ?? []) > 0)
                <div class="quality">
                    <ul>
                        @foreach ($section['data_quality'] as $note)
                            <li>{{ $note }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </section>
    @endforeach

    <div class="caveat">
        Facts and trends in this report were computed deterministically by the FinancePro reporting service from
        authoritative records. Predictions are statistical indications, never guarantees. Advisories are rule-based
        suggestions for a human decision. This report never modifies a financial record, a loan decision, a prediction
        or an insight.
    </div>
</body>
</html>