@extends('layouts.app')

@section('title', $report->report_type->label() . ' - ' . config('app.name'))

@section('page-header')
    @include('layouts.components.page-header', [
        'title' => $report->report_type->label(),
        'subtitle' => $report->organization?->name . ' · ' . ($report->branch?->name ?? 'All authorized branches') . ' · ' . $report->period_start->format('j M Y') . ' to ' . $report->period_end->format('j M Y'),
    ])
@endsection

@section('content')
    {{--
        Intelligence report detail (Phase 12.0). Read-only. Each datum carries its
        own classification label and authoritative source; the narrative is
        clearly separated from the financial data and is never a figure.
    --}}

    <div class="d-flex gap-2 mb-3">
        <a href="{{ route('ai.reports.index') }}" class="btn btn-sm btn-outline-secondary">
            <i class="bi bi-arrow-left me-1"></i>All reports
        </a>
        <a href="{{ route('ai.reports.print', $report) }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-secondary">
            <i class="bi bi-printer me-1"></i>Print
        </a>
        <a href="{{ route('ai.reports.export', $report) }}" class="btn btn-sm btn-outline-secondary">
            <i class="bi bi-download me-1"></i>Export CSV
        </a>
    </div>

    <div class="row g-3 mb-3">
        <div class="col-12">
            <div class="vicoba-card">
                <div class="card-body small text-muted">
                    <div class="row g-2">
                        <div class="col-md-3"><strong>Reporting period:</strong> {{ $report->period_start->toFormattedDateString() }} to {{ $report->period_end->toFormattedDateString() }}</div>
                        <div class="col-md-3"><strong>Comparison period:</strong>
                            @if ($report->previous_period_start)
                                {{ $report->previous_period_start->toFormattedDateString() }} to {{ $report->previous_period_end->toFormattedDateString() }}
                            @else
                                Not available
                            @endif
                        </div>
                        <div class="col-md-3"><strong>Data through:</strong> {{ $report->data_through?->toFormattedDateString() }}</div>
                        <div class="col-md-3"><strong>Generated:</strong> {{ $report->generated_at?->format('j M Y, H:i') }}</div>
                    </div>
                    <div class="mt-2 fst-italic">
                        The reporting period is the window being described. Data through is the newest authoritative
                        record this report could observe. They are shown separately so later data is never implied to
                        belong to the reporting period.
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($sections === [])
        <div class="vicoba-card">
            <div class="card-body text-center text-muted py-5">
                <i class="bi bi-file-earmark-x d-block mb-2" style="font-size: 2rem;"></i>
                This report contains no data for the selected scope and period.
            </div>
        </div>
    @endif

    @if (count($dataQuality) > 0)
        <div class="vicoba-card mb-3">
            <div class="card-header"><i class="bi bi-exclamation-triangle me-1"></i> Data quality and limitations</div>
            <div class="card-body small">
                <ul class="mb-0">
                    @foreach ($dataQuality as $note)
                        <li>{{ $note }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif

    @if (is_array($report->narrative) && ($report->narrative['available'] ?? false) === true)
        <div class="vicoba-card mb-3">
            <div class="card-header">
                <i class="bi bi-stars me-1"></i> AI narrative
                <span class="badge bg-warning text-dark ms-2">Explanatory only</span>
            </div>
            <div class="card-body">
                <div class="small text-muted mb-2">
                    Generated by {{ $report->narrative['provider'] ?? 'the AI provider' }} ({{ $report->narrative['model'] ?? 'unknown model' }}).
                    This narrative explains the figures below; it does not compute, replace or alter any of them, and it
                    never approves or rejects anything.
                </div>
                <div style="white-space: pre-line">{{ $report->narrative['summary'] }}</div>
            </div>
        </div>
@elseif (is_array($report->narrative))
            {{-- A narrative was requested and resolved as unavailable. Say so
                 explicitly rather than hiding the absence: the report itself is
                 complete and unaffected. --}}
            <div class="vicoba-card mb-3">
                <div class="card-header"><i class="bi bi-stars me-1"></i> AI narrative</div>
                <div class="card-body text-muted small">
                    The AI narrative could not be generated ({{ $report->narrative['reason'] ?? 'provider unavailable' }}).
                    The financial report below is complete and unaffected.
                </div>
            </div>
        @endif

    @foreach ($sections as $section)
        <div class="vicoba-card mb-3">
            <div class="card-header"><i class="bi bi-list-check me-1"></i> {{ $section['title'] ?? 'Section' }}</div>
            <div class="card-body">
                @foreach (['facts', 'trends', 'predictions', 'advisories'] as $group)
                    @if (count($section[$group] ?? []) > 0)
                        <div class="row g-2">
                            @foreach ($section[$group] as $datum)
                                <div class="col-12 col-lg-6">
                                    @include('ai.reports.partials.datum', ['datum' => $datum])
                                </div>
                            @endforeach
                        </div>
                    @endif
                @endforeach

                @if (count($section['rows'] ?? []) > 0)
                    <div class="mt-2">
                        @foreach ($section['rows'] as $row)
                            <div class="mt-3">
                                <div class="fw-semibold small mb-1">{{ $row['label'] ?? 'Detail' }}</div>
                                @if (count($row['rows'] ?? []) > 0)
                                    <div class="table-responsive">
                                        <table class="table table-sm small mb-0">
                                            <tbody>
                                                @foreach ($row['rows'] as $line)
                                                    <tr>
                                                        @foreach ($line as $cell)
                                                            <td class="border-0 py-1 {{ $loop->first ? 'fw-semibold' : '' }}">{{ is_array($cell) ? json_encode($cell) : $cell }}</td>
                                                        @endforeach
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                @else
                                    <div class="small text-muted">No rows available.</div>
                                @endif
                            </div>
                        @endforeach
                    </div>
                @endif

                @if (count($section['data_quality'] ?? []) > 0)
                    <div class="alert alert-light border mt-3 mb-0 small">
                        <i class="bi bi-info-circle me-1"></i>
                        <ul class="mb-0">
                            @foreach ($section['data_quality'] as $note)
                                <li>{{ $note }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
    @endforeach

    <div class="vicoba-card">
        <div class="card-body small text-muted">
            <i class="bi bi-shield-check me-1"></i>
            Facts and trends in this report were computed deterministically by the FinancePro reporting service from
            authoritative records. Predictions are statistical indications, never guarantees. Advisories are rule-based
            suggestions for a human decision. This report never modifies a financial record, a loan decision, a
            prediction or an insight.
        </div>
    </div>
@endsection