<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Proactive Intelligence (Phase 11.9)
    |--------------------------------------------------------------------------
    |
    | Deterministic, rule-based advisory insights and alerts. Every threshold
    | is configurable here; detection is a pure read over authoritative
    | FinancePro records and never changes a financial record or makes a
    | decision automatically. Values come exclusively from environment
    | variables. Changing a knob changes only what the advisory layer reports.
    |
    */

    'currency' => env('APP_CURRENCY', 'TZS'),

    /*
    | Master switch. When false, no rule is evaluated and no insight is
    | generated by the dashboard, tool or scheduler.
    */

    'enabled' => (bool) env('AI_INSIGHTS_ENABLED', true),

    /*
    | Whether a newly created insight also produces an in-app notification
    | (Laravel database notifications) for every user holding ai.insights.view
    | in the affected organization.
    */

    'notify' => (bool) env('AI_INSIGHTS_NOTIFY', true),

    /*
    | An open insight is retired (expired) when its condition stops holding and
    | it has not been regenerated for this many days. Guards against flapping
    | while keeping the open list bounded.
    */

    'stale_after_days' => (int) env('AI_INSIGHTS_STALE_AFTER_DAYS', 7),

    /*
    | Upper bound of insights persisted per organization on one generation
    | pass. Detection is ordered by severity and stops at the bound.
    */

    'max_per_organization' => (int) env('AI_INSIGHTS_MAX_PER_ORG', 50),

    /*
    | Rule: overdue loans. A loan with an outstanding installment overdue at
    | least overdue_min_days raises an insight. Severity scales with the days
    | past due (notice/warning/critical breakpoints).
    */

    'overdue_min_days' => (int) env('AI_INSIGHTS_OVERDUE_MIN_DAYS', 7),
    'overdue_warning_days' => (int) env('AI_INSIGHTS_OVERDUE_WARNING_DAYS', 30),
    'overdue_critical_days' => (int) env('AI_INSIGHTS_OVERDUE_CRITICAL_DAYS', 90),

    /*
    | Rule: maturity pressure. Active loans with outstanding balance maturing
    | within the window raise a notice once at least maturity_concentration
    | loans mature in that window at once.
    */

    'maturity_window_days' => (int) env('AI_INSIGHTS_MATURITY_WINDOW_DAYS', 30),
    'maturity_concentration' => (int) env('AI_INSIGHTS_MATURITY_COUNT', 3),

    /*
    | Rule: portfolio at risk. Delinquent principal past the PAR threshold
    | reaching par_warning_percent / par_critical_percent of total principal
    | outstanding raises the insight.
    */

    'par_threshold_days' => (int) env('AI_INSIGHTS_PAR_THRESHOLD_DAYS', 30),
    'par_warning_percent' => (float) env('AI_INSIGHTS_PAR_WARNING_PERCENT', 5.0),
    'par_critical_percent' => (float) env('AI_INSIGHTS_PAR_CRITICAL_PERCENT', 10.0),

    /*
    | Rule: loan concentration. A single loan holding at least this share of
    | total active outstanding principal raises a warning.
    */

    'concentration_ratio' => (float) env('AI_INSIGHTS_CONCENTRATION_RATIO', 0.30),

    /*
    | Rule: cash-flow shortfall. The projected cumulative net cash-flow over
    | the predictive horizon below this amount raises a warning.
    */

    'cashflow_shortfall_threshold' => (float) env('AI_INSIGHTS_CASHFLOW_SHORTFALL', 0),

    /*
    | Rule: collection decline. A drop of at least this many percentage points
    | between the current and the previous complete-month collection rate
    | raises a warning.
    */

    'collection_decline_points' => (float) env('AI_INSIGHTS_COLLECTION_DECLINE_POINTS', 20.0),

    /*
    | Rule: savings decline. Total deposits of the trailing savings_window
    | complete months below that percentage of the previous equal-length window
    | raises a notice.
    */

    'savings_window_months' => (int) env('AI_INSIGHTS_SAVINGS_WINDOW_MONTHS', 3),
    'savings_decline_percent' => (float) env('AI_INSIGHTS_SAVINGS_DECLINE_PERCENT', 20.0),

    /*
    | Rule: accounting imbalance. Journal entries left in draft for at least
    | this many days raise a notice; an unbalanced trial balance raises a
    | warning.
    */

    'journal_draft_days' => (int) env('AI_INSIGHTS_JOURNAL_DRAFT_DAYS', 7),

    /*
    | Rule: operational gap. Loan applications submitted but still pending for
    | at least this many days raise a notice. Data-quality issues reported by
    | the predictive quality gate also raise a notice when non-empty.
    */

    'operational_pending_days' => (int) env('AI_INSIGHTS_OPERATIONAL_PENDING_DAYS', 5),

];
